services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
  
  webapp:
    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    build:
      context: .
      dockerfile: Dockerfile.webapp
    depends_on:
      db:
        condition: service_healthy
    restart: always
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "9060:80"
    depends_on:
      - webapp
    restart: always
