services:
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./migrate:${DATA_PATH}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER}"]
      interval: 10s
      timeout: 10s
      retries: 3
  
  webapp:
    env_file:
      - .env
    environment:
      PGHOST: db
    build:
      context: .
      dockerfile: Dockerfile.webapp
    depends_on:
      db:
        condition: service_healthy
    restart: always
  
  nginx:
    image: nginx:latest
    env_file:
      - .env
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "${APPPORT}:80"
    depends_on:
      - webapp
    restart: always
