version: '3'

dotenv: ['.env']

tasks:
  build:
    desc: Build the application
    cmds:
      - go build -o '{{.BUILD_DIR}}'/ ./cmd/info-web
  clean:
    desc: Clean build files.
    cmds:
      - rm -rf '{{.BUILD_DIR}}'
  run:
    desc: Run the application during development.
    env:
      PGHOST: localhost
    cmds:
      - go run ./cmd/info-web
  migrate:
    desc: Migrate database during development.
    env:
      PGHOST: localhost
      DATA_PATH: '{{.TASKFILE_DIR}}/migrate'
    dir: migrate
    cmds:
      - ./migrate.sh
