version: '3'

env:
  BUILD_DIR: build
  PGDATABASE: postgres
  PGUSER: postgres
  PGPASSWORD: postgres

tasks:
  run:
    desc: Run the application during development.
    env:
      PGHOST: localhost
    cmds:
      - go run ./cmd/info-web
  build:
    desc: Build the application
    cmds:
      - go build -o '{{.BUILD_DIR}}'/ ./cmd/info-web
  clean:
    desc: Clean build files.
    cmds:
      - rm -rf '{{.BUILD_DIR}}'
  migrate:
    desc: Migrate database.
    env:
      PGHOST: localhost
      DATA_PATH: '{{.TASKFILE_DIR}}/migrate'
    dir: migrate
    cmds:
      - ./migrate.sh
